name: "hercules"

on:
  pull_request:

jobs:
  eval:
    name: ci/hercules/evaluation
    runs-on: ubuntu-latest
    if: github.repository == 'nix-community/infra' && github.event.pull_request.head.repo.fork
    steps:
      - run: echo
  default:
    name: ci/hercules/onPush/default
    runs-on: ubuntu-latest
    if: github.repository == 'nix-community/infra' && github.event.pull_request.head.repo.fork
    steps:
      - run: echo
